apiVersion: v1
kind: Service
metadata:
  name: recommendation-api-service
  labels:
    app: recommendation-api
spec:
  type: LoadBalancer  # Use NodePort if LoadBalancer is not available in your cluster
  selector:
    app: recommendation-api
  ports:
    - protocol: TCP
      port: 80             # External port
      targetPort: 8000     # Port on which the container is running
